### ISSUE TITLE
Tests needed

### ISSUE THREAD

**Issue by HacKanCuBa** [tadfisher/pass-otp#1]
You need to write some tests to verify this extension on every future update. You can take a look at the [tests written for Pass](https://git.zx2c4.com/password-store/tree/tests), they use Sharness and it's very easy to use.

Cheers!

**Comment by roddhjav** [comment]
+1

You can also use a more simple test suite. For instance the one [I have in pass-tomb](https://github.com/roddhjav/pass-tomb/tree/master/tests). This test suite is adapted from the test suite in [tomb itself](https://github.com/dyne/Tomb/tree/master/extras/test). Once this done, you should be able to use Travis (or other) to run them.

**Comment by HacKanCuBa** [comment]
True, I used those tests in my extensions too (now I'm planning to migrate to sharness).

**Comment by tadfisher** [comment]
There are a whole bunch of tests, and adding them has made working on this project much, much easier.

Thank you both!

**Comment by HacKanCuBa** [comment]
Great!! :D
