### ISSUE TITLE
Using the right PREFIX

### ISSUE THREAD

**Issue by rnkn** [tadfisher/pass-otp#110]
Hello,

Thanks for putting the work into making this 👍

A quick note about your Makefile, I know that some Linuxes put stuff into `/usr` when they shouldn't, but to consult `man hier`...
~~~
/usr/local
    This is where programs which are local to the site typically go.
~~~
Using `/usr` is a bit of an endemic no-no, but if we all work together, we can make a difference!

Again, much appreciation for the time you've put into this.

**Comment by tadfisher** [comment]
You can set `PREFIX` to whatever you'd like with `make PREFIX=$dir`. Are you reporting about the default value?

**Comment by rnkn** [comment]
Default yep. I've installed via Homebrew so this is more a "greater good" thing.

**Comment by tadfisher** [comment]
I believe the Homebrew recipe needs to be changed to set an alternate PREFIX, then.

**Comment by rnkn** [comment]
Homebrew works perfectly. I'm trying to enact a cultural change here man! Down with `/usr`! All hail `/usr/local`! (Feel free to close this issue..)
