### ISSUE TITLE
which dependency missing

### ISSUE THREAD

**Issue by acidvegas** [tadfisher/pass-otp#115]
the program "which" is required for finding oathtool and is not a listed dependncy for this.
My arch linux build did not come with which installed by default and pass otp was failing saying it could not find oathtool due to this. I installed whiched, which fixed this issue.

**Comment by lanodan** [comment]
[2020-05-18 12:41:50-0700] Dionysus:
> the program "which" is required for finding oathtool and is not a listed dependncy for this.
> My arch linux build did not come with which installed by default and pass otp was failing saying it could not find oathtool due to this. I installed whiched, which fixed this issue.

I guess pass-otp should be modified so that it uses command(1) (POSIX standard) or type (bash builtin).

**Comment by roddhjav** [comment]
I agree and I already proposed the fix in #116
