### ISSUE TITLE
hi ,i am triyng to export otp from google authenticator ,,,,,but i get thiis..

### ISSUE THREAD

**Issue by MartinEtcheverry** [tadfisher/pass-otp#125]
zbarcam -q --raw | pass otp insert some_secre
Cannot parse OTP key URI: otpauth-migration://offline?data=xxxx.......

any clues?

**Comment by tadfisher** [comment]
That is the most harebrained scheme I have yet seen, and I'm not going to support it. Essentially they're encoding everything as a Google Authenticator-specific protobuf message which would need yet more code and dependencies to handle. Just issue new OTP tokens for your services, don't try to migrate codes out of Google Authenticator.

**Comment by MartinEtcheverry** [comment]
oh...ok , thanks for taking the time to respond!

**Comment by anevolbap** [comment]
I found this [repo](https://github.com/digitalduke/otpauth-migration-decoder) useful to parse the Google Authenticator weird link.
