### ISSUE TITLE
Error: otp is not in the password store. pass version: 1.7.3

### ISSUE THREAD

**Issue by svblsvljb** [tadfisher/pass-otp#135]
Hi

i have pass v1.7.3 installed from source i install a pass-otp but pass looking for otp as a password not as extension

I install pass-otp from source too and had "pass-otp is installed succesfully"

Maybe this is becouse i am using zsh?

I dont really know what is problem.

**Comment by yggdr** [comment]
Sounds like you didn't activate extensions in pass:
export PASSWORD_STORE_ENABLE_EXTENSIONS=true

Maybe even a
export PASSWORD_STORE_EXTENSIONS_DIR=$HOME/.password-store/.extensions

**Comment by svblsvljb** [comment]
This 2 commands doesnt change anything and i havent ~/.password-store/.extensions dir.

Other pass extensions like pass import works well. 

I inited pass in default ~/.password-store dir and gpg-id file exists.

**Comment by StarrWulfe** [comment]
Same same.

Cannot use on MacOS 11 if that makes a difference. Built from source and also Homebrew -- same result.  

I'm using fish so maybe it only works as a bash command?

**Comment by StarrWulfe** [comment]
I found the problem... It installs `pass-otb` into  `usr/local/lib/password-store/extensions/` by default. In my case I had to then do `export PASSWORD_STORE_EXTENSIONS_DIR=/usr/local/lib/password-store/extensions/` then `export PASSWORD_STORE_ENABLE_EXTENSIONS=true` to let pass see the extension.

**Comment by svblsvljb** [comment]
This works, THX!

**Comment by svblsvljb** [comment]
Dont forget to add this to your .zshrc || .bashrc
