### ISSUE TITLE
Any way to differentiate between pass-otp generated gpg files without decryption?

### ISSUE THREAD

**Issue by rupansh** [tadfisher/pass-otp#139]
Hi! I am the developer of https://github.com/rupansh/passmenu-rs
Recently pass-otp support was added to it.
It would be nice if there was a way to differentiate between normal pass files and pass-otp files without decryption.

**Comment by tadfisher** [comment]
It would be nice, but I'm not sure this is the place to implement it. Essentially what you want is an index of files matching some filter that is updated whenever password files are added, changed, or removed. This is not something that would be specific to pass-otp and so I don't really want to invest the time and effort to create and maintain code which manages an index.

**Comment by rupansh** [comment]
understandable
