### ISSUE TITLE
yandex yaotp support

### ISSUE THREAD

**Issue by 532910** [tadfisher/pass-otp#140]
Could you add `yaotp` method please.

https://github.com/norblik/KeeYaOtp
https://play.google.com/store/apps/details?id=ru.yandex.key

**Comment by tadfisher** [comment]
It looks like Yandex is a standard TOTP mechanism with the following parameters:

- `digits=8`
- `algorithm=sha256`

Formatting the `otpauth://` URL as the following should work:

`otpauth://totp?<account>@yandex.ru?secret=<secret>&digits=8&algorithm=sha256`

Feel free to reopen if this doesn't solve the issue.

**Comment by 532910** [comment]
yaotp is not a function of time (only) but on pin code also.
