### ISSUE TITLE
Using pass-otp with addons.mozilla.org

### ISSUE THREAD

**Issue by ghost** [tadfisher/pass-otp#143]
Hello and thank you for your work!

There are reports of pass-otp working with Mozilla's 2FA (https://blog.mozilla.org/addons/2021/03/11/two-factor-authentication-required-for-extension-developers/)

However, now Mozilla is not giving me the otpauth:// , it is only giving me a set of 16 alphanumerics.

How do I import them into pass-otp?

**Comment by ghost** [comment]
There have been reports (https://www.opennet.ru/openforum/vsluhforumID3/124465.html#204) that the otpauth:// should like something like:

`otpauth://totp/000000@Bitstamp?secret=A23UCSQTHJADET2I`

However, on my machine it still does not work, complaining about:

```
can't connect to 'socket:///home/lockywolf/.gnupg/log-socket': Connection refused
OTP secret encryption aborted.
```

**Comment by tadfisher** [comment]
You can enter the secret using `pass otp insert --secret` and it will generate a URI for you. See `pass otp --help` for more options.
