### ISSUE TITLE
`pass init` fails with newest gnupg

### ISSUE THREAD

**Issue by SMillerDev** [tadfisher/pass-otp#147]
When running `pass init` on gnupg 2.3.3 on macOS `htop-secret` seems to fail.
This is likely related to https://dev.gnupg.org/T5656

```
==> pass init Testing
Password store initialized for Testing
gpg: error reading symlink '/proc/curproc/file': No such file or directory
hotp-secret: passfile not found.
```

**Comment by maksimyugai** [comment]
The issue appears not only while `pass init`. It completely blocked using the pass. 

> ~ ❯ pass -c  amazon/aws.amazon.com
gpg: error reading symlink '/proc/curproc/file': No such file or directory
gpg: WARNING: server 'gpg-agent' is older than us (2.3.2 < 2.3.3)
gpg: public key decryption failed: No pinentry
gpg: decryption failed: No pinentry

**Comment by Jberlinsky** [comment]
I'm experiencing the same failure mode.

**Comment by Jberlinsky** [comment]
See https://github.com/Homebrew/homebrew-core/pull/87155#issuecomment-951350524 for a quick remediation option. Obviously not ideal, but it'll get affected folks back to a working state pending upstream fixes.

**Comment by maksimyugai** [comment]
Ok, it works after MacBook restarting. Just remained:

`gpg: error reading symlink '/proc/curproc/file': No such file or directory`

No blocking.

**Comment by tadfisher** [comment]
This should be raised upstream, `otp` just calls `pass` functions to do decryption.
