### ISSUE TITLE
generated otp code is not correct

### ISSUE THREAD

**Issue by formula-spectre** [tadfisher/pass-otp#183]
I have the same uri on aegis autheticator on my phone and on pass on my desktop, and there is a mismatch; I don't know what to provide, so 
pass version: 1.7.4
zbar version: 0.23.92
oath-toolkit version: 2.6.7
distro: gentoo

**Comment by yohannd1** [comment]
I've recently noticed my OTP codes are not matching the ones I have in Authy. Not fully sure when this started to happen, but it used to work fine before. Also using `pass 1.7.4`.

**Comment by zoj613** [comment]
Same here. I recently experienced this on linkedin. Using OTP with Aegis as the authentication app works well, but if I take the same URI and insert in on pass-otp, the generated OTP does not work.

EDIT: I was able to resolve this using the suggestion made here: https://github.com/tadfisher/pass-otp/issues/138#issuecomment-782767357

@formula-spectre

**Comment by sereinity** [comment]
TOTP (timed one time password) relies on the clock to generate the code, it's mandatory to have a device that has its clock correctly configured. It's not a bug of pass-otp.

One way to ensure that a device has its clock correctly configured is to rely on a NTP service as said in https://github.com/tadfisher/pass-otp/issues/138#issuecomment-782767357

**Comment by formula-spectre** [comment]
apologies for the late response. I'm not gonna lie, I forgot about this issue completely.  
installed chrony as an NTP, and now the generated tokens are correct. thanks!
