### ISSUE TITLE
Upgrade path from older versions of pass-otp

### ISSUE THREAD

**Issue by hughdavenport** [tadfisher/pass-otp#25]
Just updated to 1.0.0 and noticed that I'm not using the old format, is there an upgrade path, or should I just manually do it.

Also, for what its worth, I think that having default settings, and just asking for a secret as opposed to the URI input (maybe as a flag?).

Cheers,

Hugh

**Comment by tadfisher** [comment]
Migration instructions are provided in the [readme](https://github.com/tadfisher/pass-otp#migrating-from-pass-otp-01); it's a manual process, yes.

What services provide an OTP secret only, and not an `otpauth://` URI or QR code?

**Comment by hughdavenport** [comment]
Ah sorry missed that bit at the bottom, no worries i can script that. Unsure of any services off top of head but i think I've seen some in my day. Will close this though as that probably shouldn't be good practise.
