### ISSUE TITLE
Mac make install

### ISSUE THREAD

**Issue by yishilin14** [tadfisher/pass-otp#26]
Hi. I am using Mac. Instead of `sudo make install`, I installed pass-otp via `make install PREFIX=/usr/local` (without sudo).

This is not an issue. Just don't know where to put this comment about "readme". :-)

**Comment by q1x0te** [comment]
Hi @yishilin14, 

Did you manage to install also its dependency oathtool in a macOS?

Thanks

**Comment by yishilin14** [comment]
@q1x0te I did `brew install oath-toolkit`, just like you.
