### ISSUE TITLE
Error: otp is not in the password store

### ISSUE THREAD

**Issue by q1x0te** [tadfisher/pass-otp#27]
Hi,

I just installed pass-otp in Ubuntu, got the message "pass-otp installed successfully", but when I run any pass otp command I have this:

Error: otp is not in the password store

As if it wasn't installed. Am I missing something?

**Comment by roddhjav** [comment]
What version of `pass` do you have? pass-otp requires `pass` 1.7.0 or later for extension support.

**Comment by q1x0te** [comment]
The version I have (installed via Ubuntu apt-get) is the 1.6.5-3.

I should then install manually the 1.7.0 or the latest from the website
right?

On Apr 14, 2017 00:02, "Alexandre PUJOL" <notifications@github.com> wrote:

What version of pass do you have? pass-otp requires pass 1.7.0 or later for
extension support.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tadfisher/pass-otp/issues/27#issuecomment-294033393>,
or mute the thread

**Comment by tadfisher** [comment]
Not a `pass-otp` issue.
