### ISSUE TITLE
Different code with same secret (google authenticator/pass-otp)

### ISSUE THREAD

**Issue by rodrigogolive** [tadfisher/pass-otp#30]
Hi, first time using pass-otp (migrating passwords to pass recently).
I have got the URI from a qrcode, manually added to google authenticator and at the same time to pass-otp.
Both generate codes, but just the one from google authenticator works. Tested pass-otp on linux and osx, several times (deleting, generating new qrcode/uri, adding).

Any thoughts on this? Is something related to timezone (-3 here, Brazil)?

Thanks for this extension ;)

**Comment by tadfisher** [comment]
Is this an HOTP code? Can you paste the otpauth:// url with the issuer and name removed?

**Comment by rodrigogolive** [comment]
no, this is a totp one (gitlab):
otpauth://totp/REMOVED:REMOVED?secret=REMOVED&issuer=REMOVED

**Comment by tadfisher** [comment]
I'll test out gitlab 2FA later today.

**Comment by rodrigogolive** [comment]
OK, will test with some other services as well later and report back, thanks!

**Comment by rodrigogolive** [comment]
I had some time and tested with two more sites: Slack and Amazon.

They both worked as expected (a little skew of 2-3 seconds from the generation on GA to pass-otp).

Was about to delete the one from gitlab and re-add it, but now it is working as expected (without 2fa recreation), but just tested on osx, as will have access to my linux desk tonight, so will test there again and migrate some more services/sites to see the behavior.

Also, all have the same uri scheme from the [gitlab one](https://github.com/tadfisher/pass-otp/issues/30#issuecomment-300796286).

Will report back later, thanks

**Comment by tadfisher** [comment]
Yep, I'm guessing clock skew is the problem. Make sure your devices are synced to a well-known time source, i.e. using NTP.

This happens because the default totp period is 30 seconds, and significant skew will result in generating a different code from what the server expects.

I suspect Gitlab is being fairly strict about the clock window and is only allowing codes within that 30-second period.

**Comment by tadfisher** [comment]
Closing, feel free to repoen if you notice further issues.
