### ISSUE TITLE
[Feature Request] Firefox Addon

### ISSUE THREAD

**Issue by balasankarc** [tadfisher/pass-otp#32]
`pass` already has a [Firefox addon](https://addons.mozilla.org/en-US/firefox/addon/passff/). It would be great if we could integrate pass-otp to it.

**Comment by tadfisher** [comment]
I'm not really able to work on that. You might try filing a bug in their repo.

I'd suggest asking for a way to run a generic `pass` command on a passfile, so other extensions could benefit from such an addition as well.

**Comment by balasankarc** [comment]
I filed a bug in their repo. https://github.com/passff/passff/issues/200 . Thank you.
