### ISSUE TITLE
No output on running `pass otp`

### ISSUE THREAD

**Issue by samdmarshall** [tadfisher/pass-otp#39]
I recently installed pass 1.7.1 on Ubunutu 17.04 and then installed this plugin to support my 2fa tokens. However whenever i run the `pass otp show foo/bar` command, I get an empty line of output instead of the expected 2fa code. I have `oathtool` installed and the exit code of the `pass otp show` command is zero, so i have to assume that everything is being run correctly. I have the same setup on an OS X 10.12 machine that works fine.

**Comment by greg-minshall** [comment]
in otp.bash, "local cmd" is not initialized.  if no line in the (decrypted) pass file matches the otpauth pattern, otp_parse_uri() is never called, so uri_type is not set, so no branch of the case statement is taken, so the variable cmd is not set to any other value.  with, at least bash(1), "$()" returns a zero exit code.  the result follows (as they say).

so, you should look and see if your otpauth statement is correctly specified.

**Comment by samdmarshall** [comment]
It looks like the flaw here is that I am using the old format of the otp keys that is mentioned in the readme. So now I guess I have to convert all my otp codes to use this new URI format to get pass-otp to work again? this feels like the script should update for me if the old format is going to be broken and not-supported anymore.
