### ISSUE TITLE
pass-otp is now in [community]

### ISSUE THREAD

**Issue by roddhjav** [tadfisher/pass-otp#42]
`pass-otp` has been moved in the official [community repository of archlinux](https://www.archlinux.org/packages/community/any/pass-otp/), therefore it is not in the AUR any-more. You should update the README to this fit change.

It also means, [Foxboron](https://www.archlinux.org/packages/?maintainer=Foxboron) is the new arch maintainer of pass-otp.

**Comment by tadfisher** [comment]
Awesome! Updated the README.
