### ISSUE TITLE
Doesn't add to git

### ISSUE THREAD

**Issue by hughdavenport** [tadfisher/pass-otp#5]
Normall when I insert a password, it is added to a git commit. When using pass-otp to add an otp commit, it doesn't.

**Comment by hughdavenport** [comment]
Happy to work on this myself when I get a chance, just storing here so I don't forget :)

**Comment by roddhjav** [comment]
I think this issue will be fixed by #4.

**Comment by hughdavenport** [comment]
Oh wow sorry i didn't see that when i looked at open issues. This is clearly a dup so will close this
