### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by innir** [tadfisher/pass-otp#51]
Hi,

I really like your pass extension and want to package it for Debian.
There are some improvements in the code since the last release and I'd like to ship them to the Debian users. Would you mind releasing a new version which I could pick for Debian?

Thanks,

Philip

**Comment by tadfisher** [comment]
Version 1.1.0 has been pushed.

**Comment by lanodan** [comment]
I think version 1.1.1 should be released soon as there was quite a lot of fixes done and it could avoid package maintainers to ship additional patches for them.
