### ISSUE TITLE
Sign releases

### ISSUE THREAD

**Issue by innir** [tadfisher/pass-otp#54]
Could you please sign releases with your GPG key? This would make it possible to check if the content of the tarball is really what you released.

There is a documentation how to do that if you need guidance: 

https://wiki.debian.org/Creating%20signed%20GitHub%20releases

Thanks,

Philip

**Comment by tadfisher** [comment]
Signature is attached to the `v1.1.0` release.

**Comment by polyzen** [comment]
https://lobste.rs/s/jdm7vy/github_auto_generated_tarballs_vs

**Comment by tadfisher** [comment]
@polyzen Good point, I'll upload the source archive and signature separately.
