### ISSUE TITLE
Testing fails

### ISSUE THREAD

**Issue by lanodan** [tadfisher/pass-otp#58]
I tried to run the testing part and there is some that are failing, qrencode is present btw (even if qrcode is disabled in the USE flags).

* ebuild: https://hacktivis.me/git/overlay/file/app-admin/pass-otp/pass-otp-1.1.0.ebuild.html
* [build.log](https://github.com/tadfisher/pass-otp/files/1779366/build.log)
* [system information](https://github.com/tadfisher/pass-otp/files/1779372/emerge--info-pass-otp.txt) (there is a lot of noise in there, specially in the middle…)
  * Pass version: 1.7.1

**Comment by innir** [comment]
Same here when building for Debian. I guess it's a problem of interactive shell vs. non-interactive shell. As all tests pass for me in an interactive shell...

**Comment by lanodan** [comment]
I tried putting ``SHELL="bash -i"`` in the ebuild but it doesn’t work, I think bash is frozed waiting for something it usually gets when it’s actually interactive.
I guess the tests would need to be modified for non-interactive shell.

**Comment by innir** [comment]
@lanodan Yes, I guess so too, the tests need to be modified.

**Comment by tadfisher** [comment]
How do the Debian and Gentoo packages perform testing with `pass`? I'm using the same setup.

**Comment by innir** [comment]
In Debian `make test` is invoked in my case. I think the main difference is that no tty is attached. A short summary about the build network is here: https://wiki.debian.org/buildd

**Comment by lanodan** [comment]
In gentoo it seems to be basically the same, ``make test`` is tested by default and no TTY is attached. (probably so the output can be logged).
The difference that I spot is that bash is the default shell in Gentoo while it’s dash in Debian, but it’s not much important as you’re declaring the shell.

**Comment by tadfisher** [comment]
Ok, I think `expect` is not working in these environments. I'll take a look.

I'm having difficulty reproducing the environment with no TTY, however. Any tips?

**Comment by lanodan** [comment]
``bash -c`` is non-interactive

**Comment by tadfisher** [comment]
@lanodan `make test` works fine here with `bash -c`. I think the tty-less env is what is messing things up, but appending ` </dev/null` doesn't seem to break anything.

I've tried:

```
make test </dev/null
bash -c "make test" </dev/null
bash -c "make test </dev/null"
test/insert.t </dev/null
bash -c "test/insert.t" </dev/null
bash -c "test/insert.t </dev/null"
```

**Comment by innir** [comment]
Yes, it seems not easy to reproduce :-( I use pbuilder[1] to build the packages. You'd need all the Debian packaging stuff though (I could send you if needed).

[1] A How-to can be found here https://wiki.ubuntu.com/PbuilderHowto

**Comment by tadfisher** [comment]
Can someone post the output with `TEST_OPTS="-v"` set?

**Comment by innir** [comment]
here you go: https://gist.github.com/innir/4e24fcfd7a25dcbcdd48bd39682a66ff

Oh: `./sharness.sh: line 335: expect: command not found`

**Comment by tadfisher** [comment]
Aha!

**Comment by innir** [comment]
OK, works with installed `expect`

You could probably mention that (at least on Debian)  `expect`, `git`, `oathtool` and `pass` (>= 1.7.0) are needed to run the tests.

**Comment by tadfisher** [comment]
Added build requirement documentation here: https://github.com/tadfisher/pass-otp#build-requirements

Hopefully this helps future packaging efforts.

**Comment by innir** [comment]
@tadfisher Great, thanks!

**Comment by lanodan** [comment]
Works here now too!

**Comment by tadfisher** [comment]
@innir @lanodan If you could PR install instructions for Debian and Gentoo that'd be awesome. Thanks for packaging this!
