### ISSUE TITLE
pass-otp is available on gentoo

### ISSUE THREAD

**Issue by lanodan** [tadfisher/pass-otp#70]
Sorry for the late notification (my PR for pass-otp got merged on 2018-03-16).
Installation is done with the usual/regular ``emerge app-admin/pass-otp`` so you might want to just say it’s available on gentoo.

**Comment by tadfisher** [comment]
Thanks, I'll add it to the readme in a bit.

**Comment by lanodan** [comment]
It’s been almost two months…
