### ISSUE TITLE
Import OTP secrets from Android Google Authenticator database

### ISSUE THREAD

**Issue by brainstorm** [tadfisher/pass-otp#74]
Super useful little add-on to `pass`, thanks for this @tadfisher!

Has it crossed your mind to put a small migrator from [Google Authenticator](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en_us) to `pass-otp`.

On a rooted Android handset it's as easy as [dumping the corresponding sqlite3 database from the corresponding directory](https://android.stackexchange.com/questions/63252/how-do-i-back-up-google-authenticator#86861). Then this silly bit of sqlite/bash script did the trick for me in order to convert rows into `pass-otp` urls:

```bash
#!/bin/bash

sqlite_run="sqlite3 -batch $HOME/tmp/foo"

# After dumping the database from a rooted android phone using the following SO hints:
# https://android.stackexchange.com/questions/63252/how-do-i-back-up-google-authenticator#86861
#
#sqlite> .schema accounts
#CREATE TABLE accounts (_id INTEGER PRIMARY KEY, email TEXT NOT NULL, secret TEXT NOT NULL, counter INTEGER DEFAULT 0, type INTEGER, provider INTEGER DEFAULT 0, issuer TEXT DEFAULT NULL, original_name TEXT DEFAULT NULL);

# The idea is to extract and convert this:
#$ sqlite3 -batch ~/tmp/foo "select * from accounts;"
#2|Google:johndoe@example.com|SECRET|0|0|0|Google|Google:johndoe@example.com
#
# To this:
#otpauth://totp/johndoe@example.com@Google?secret=SECRET&issuer=Google

for id in $($sqlite_run "select _id from accounts;"); do
    email=$($sqlite_run "select email from accounts where _id=$id")
    secret=$($sqlite_run "select secret from accounts where _id=$id")
    issuer=$($sqlite_run "select issuer from accounts where _id=$id")
    echo "otpauth://totp/${email}?secret=${secret}&issuer=${issuer}"
done
```

**Comment by tadfisher** [comment]
Maybe we can add a wiki article and link it to the README. I'm not really interested in maintaining this, as I don't have a rooted Android device and I don't use Google Authenticator.

**Comment by brainstorm** [comment]
Fair enough, although this repo's wiki doesn't seem to be accessible/editable for third parties as of now, according to SO:

https://stackoverflow.com/questions/15080848/how-do-i-clone-a-github-wiki#15080850

```bash
$ git clone https://github.com/tadfisher/pass-otp/wiki pass-otp-wiki
Cloning into 'pass-otp-wiki'...
fatal: unable to update url base from redirection:
  asked for: https://github.com/tadfisher/pass-otp/wiki/info/refs?service=git-upload-pack
   redirect: https://github.com/tadfisher/pass-otp
$ git clone https://github.com/tadfisher/pass-otp.wiki pass-otp-wiki
Cloning into 'pass-otp-wiki'...
fatal: remote error: access denied or repository not exported: /0/nw/05/41/20/142236406/82002997.wiki.git
```

**Comment by tadfisher** [comment]
Yep, I just turned it on. I'll add you as a collaborator in just a sec.

**Comment by brainstorm** [comment]
Closing via:

https://github.com/tadfisher/pass-otp/wiki/How-to-migrate-your-Google-Authenticator-database-to-pass-otp%3F
