### ISSUE TITLE
qrcode utility doesn't exist on macOS

### ISSUE THREAD

**Issue by belak** [tadfisher/pass-otp#78]
I ended up updating the call to `qrcode` to be `qrencode -t ANSI -o - "$otp_uri" "OTP key URI for $path"` to display the QR code for importing elsewhere.

**Comment by tadfisher** [comment]
`qrcode` is a Bash function in the `pass` script itself, which sources this extension. If upstream isn't calling the correct command on macOS, I'd report a bug on the mailing list.

Closing for now, as this isn't something I'd want to work around here (and it works on Linux).
