### ISSUE TITLE
Release Tarball

### ISSUE THREAD

**Issue by lanodan** [tadfisher/pass-otp#83]
It’s probably too late now as it’s published but the tarball tree is using ``pass-otp-version`` as a root directory instead of ``pass-otp-1.1.1`` which is quite the standard and what you used before.

**Comment by lanodan** [comment]
> I'll fix it and re-upload.
It’s quite early so you can maybe still do that, but rewriting tarballs is a bad idea as it breaks hashes in ports, I think you should at least put the corrected ones with a different name.

**Comment by tadfisher** [comment]
I'd rather the hashes break, and ports are likely broken since they would probably try to traverse the `pass-otp-1.1.1` directory.

**Comment by lanodan** [comment]
That’s if you try to bump the port without testing it, which would/should never be done.

**Comment by tadfisher** [comment]
Thanks, I'll keep this in mind in the future.
